name: data-sharing between jobs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create build file
        run: echo "Hello World" > app.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-file
          path: app.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-file

      - name: Deploy
        run: cat app.txt